vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|10 Mar 2008 03:57:44 -0000
vti_author:SR|VANI\\Administrador
vti_modifiedby:SR|VANI\\Administrador
vti_nexttolasttimemodified:TW|10 Mar 2008 03:57:44 -0000
vti_timecreated:TR|22 Oct 2012 17:54:57 -0000
vti_cacheddtm:TX|22 Oct 2012 17:54:57 -0000
vti_filesize:IR|126132
vti_extenderversion:SR|12.0.0.6211
vti_backlinkinfo:VX|1__________________________________ON_LINE/COMPRADLIS.brillantes.htm 1__________________________________ON_LINE/index.scroll.htm 1__________________________________ON_LINE/index.anterior.htm 1__________________________________ON_LINE/COMPRADLIS.vidrios.htm 1__________________________________ON_LINE/COMPRADLIS.relojes.htm 1__________________________________ON_LINE/COMPRADLIS.gracias.htm 1__________________________________ON_LINE/_muestra1_/DLIS.brillantes.htm 1__________________________________ON_LINE/_muestra1_/DLIS.joyas.htm 1__________________________________ON_LINE/COMPRADLIS.joyas.htm 1__________________________________ON_LINE/_muestra1_/DLIS.monedas.htm 1__________________________________ON_LINE/_muestra1_/DLIS.plateria.htm 1__________________________________ON_LINE/index.htm 1__________________________________ON_LINE/COMPRADLIS.index.htm 1__________________________________ON_LINE/_muestra1_/DLIS.antiguedades.htm 1__________________________________ON_LINE/COMPRADLIS.antiguedades.htm 1__________________________________ON_LINE/COMPRADLIS.monedas.htm 1__________________________________ON_LINE/COMPRADLIS.plateria.htm 1__________________________________ON_LINE/_muestra1_/DLIS.relojes.htm 1__________________________________ON_LINE/_muestra1_/DLIS.vidrios.htm 1__________________________________ON_LINE/COMPRADLIS.comollegar.htm
